name: Build and Release Go Application
on:
  push:
    branches: [ main ]
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      security-events: write
      statuses: write
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Build and Release
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: |
        go build -o myapp_${{ matrix.os }}_${{ matrix.arch }} .
        git tag $(git describe --tags --abbrev=0)-${{ matrix.os }}-${{ matrix.arch }}
        git push --tags -f
        gh release upload $(git describe --tags --abbrev=0)-${{ matrix.os }}-${{ matrix.arch }} myapp_${{ matrix.os }}_${{ matrix.arch }} --clobber
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
