name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    permissions: write-all
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Build
        run: go build -o hibercli-${{ matrix.os }} .

      - name: Create Tag
        id: create_tag
        if: success()
        run: |
          echo "What's the name of the new tag?"
          read tag_name
          git tag $tag_name
          git push origin $tag_name

      - name: Create Release
        id: create_release
        if: success()
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.stdout }}
          release_name: Release ${{ steps.create_tag.outputs.stdout }}
          draft: false
          prerelease: false
          body: |
            This is the release body
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
