# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      # Lancer la commande go build -o hibercli-macos ./... puis le mettre dans les releases du repo github.com/el2zay/hibercli avec le tag 0.0.1
      run: |
        go build -o hibercli-macos ./...
        mkdir -p ${{ github.workspace }}/release
        mv hiberclimacos ${{ github.workspace }}/release/hiberclimacos
        cd ${{ github.workspace }}/release
        tar -czvf hiberclimacos.tar.gz hiberclimacos
        mv hiberclimacos.tar.gz ${{ github.workspace }}/release/hiberclimacos.tar.gz
        cd ${{ github.workspace }}
        ls -la ${{ github.workspace }}/release
