# Actions qui sont lancées à chaque push sur la branche main. Elle créé un build pour linux et la publie dans les releases.
name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go 1.19
      uses: actions/setup-go@v1
      with:
        go-version: 1.19
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
