name: Go

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        arch: ["ARM32", "x64"]
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: |
          go build -o hibercli-${{ matrix.os }}-${{ matrix.arch }} .
          which hibercli-${{ matrix.os }}-${{ matrix.arch }}
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Release Upload
        uses: d1ceward/draft-assets-release-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: hibercli-${{ matrix.os }}-${{ matrix.arch }}
