name: Go

# push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        arch: ["ARM32", "x64"]
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build -o hibercli-${{ matrix.os }}-${{ matrix.arch }} .

        
      - name: Get upload_url
        run: echo "::set-output name=upload_url::https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets{?name,label}"  
        id: release

      - name: Upload Hibercli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.STAABM_TOKEN }}
        with:
          asset_path: ./hibercli-${{ matrix.os }}-${{ matrix.arch }}
          asset_name: hibercli-${{ matrix.os }}-${{ matrix.arch }}
          asset_content_type: application/octet-stream
          upload_url: ${{ steps.release.outputs.upload_url }}
