# Actions qui sont lancées à chaque fois qu'il y a un nouveau tag
name: Go
on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go
      - name: Build
        run:
          go build -o hibercli-${{matrix.os}} .
      - name: Get latest release
        id: latest_release
        uses: actions/github@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: el2zay/hibercli
          ref: latest
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_release.outputs.upload_url }}
          asset_path: ./hibercli-${{matrix.os}}
          asset_name: hibercli-${{matrix.os}}
          asset_content_type: application/octet-stream
