name: Go

on:
  release:
    types:
      - published


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build -o hibercli-${{ matrix.os }}-${{ matrix.arch }} .

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: hibercli-${{ matrix.os }}-${{ matrix.arch }}
          path: ./hibercli-${{ matrix.os }}-${{ matrix.arch }}


  release:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          path: hibercli-${{ matrix.os }}-${{ matrix.arch }}
          
      - name: "Checkout"
        uses: "actions/checkout@v2"
        
      - name: "Get upload_url"
        run: echo "::set-output name=upload_url::https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets{?name,label}"  
        id: release

      - name: "Upload cs2pr"
        uses: "actions/upload-release-asset@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.STAABM_TOKEN }}
        with:
          asset_content_type: "text/plain"
          asset_name: "cs2pr"
          asset_path: "cs2pr"
          upload_url: ${{ steps.release.outputs.upload_url }}
