name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
      
    - name: Build binary
      run: go build -o hibercli-${{ matrix.os }} .
      
    - name: Check if tag exists
      id: check_tag
      run: echo ::set-output name=exists::$(git tag --list | grep -q "0.0.2" && echo true || echo false)
      
    - name: Create release
      if: steps.check_tag.outputs.exists == 'false'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: '0.0.2'
        release_name: '0.0.2'
        draft: false
        prerelease: false
        
    - name: Upload binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./hibercli-${{ matrix.os }}
        asset_name: hibercli-${{ matrix.os }}
        asset_content_type: application/octet-stream
